language: generic 
sudo: required
services:
  - docker

before install:
  - docker build -t the-hyphen-user/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true the-hyphen-user/docker-react npm run test